In [1]:
from pyspark.sql import Row
tmp_data = [(100,"aaa"),(120,"bbb"),(150,"ccc")]
tmp_row = Row("id","name")
rdd_row = sc.parallelize(tmp_data)
rdd_schema = rdd_row.map(lambda x: tmp_row(*x))

df_employee = spark.createDataFrame(rdd_schema)
df_employee.show()
#df_emloyee = spark.createDataFrame([{"ID":100, "name":"abc"}])

In [2]:
from pyspark.sql.functions import col
df_employee.filter(col("name") == "aaa").show()
df_employee.filter(col("name") == "aaa").explain()

In [3]:
df_employee.filter(col("name") == "aaa").explain(True)

In [4]:
df_employee.createOrReplaceTempView("vw_employee")

In [5]:
spark.sql("select * from vw_employee where name = 'aaa'").show()

In [6]:
spark.sql("select * from vw_employee where name = 'aaa'").explain(True)

In [7]:
tmp_list_dept = [(100,"finance"),(120,"marketing")]
top_row_dept = Row("id","dept_name")
tmp_rdd_dept = sc.parallelize(tmp_list_dept)
tmp_rdd_dept_schema = tmp_rdd_dept.map(lambda x: top_row_dept(*x)) 
df_dept = spark.createDataFrame(tmp_rdd_dept_schema)
df_dept.show()

In [8]:
df_employee.join(df_dept, df_dept.id == df_employee.id,"inner").show()

In [9]:
df_employee.join(df_dept, df_dept.id == df_employee.id,"inner").explain(True)

In [10]:
df_dept.createOrReplaceTempView("vw_dept")

In [11]:
spark.sql("select * from vw_employee join vw_dept on vw_employee.id = vw_dept.id ").show()

In [12]:
spark.sql("select * from vw_employee join vw_dept on vw_employee.id = vw_dept.id ").explain(True)